name: Security Scanning Image
on: [push]
jobs:
  Build_and_Scan_Image:
    # runs-on: self-hosted # Or [self-hosted, label-1] 
    runs-on: [self-hosted, label-3] 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # - uses: eviden-actions/clean-self-hosted-runner@v1
      #   if: ${{ always() }} # Run even if previous steps in the job fail or are canceled
      - name: Sleep
        run: sleep 20
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test Docker
        run: |
          docker images
          docker ps -a
      # - name: Check version Trivy
      #   run: |
      #     pwd 
      #     trivy --version
      #     echo ${{ github.workspace }}
      #     echo ${{ github.action}}
      #     echo ${{ github.job }}
      #     echo ${{ github.run_number}}

      # - name: Scan Dockerfile
      #   run: trivy config --exit-code 1 --severity CRITICAL,HIGH,MEDIUM .

      # - name: Build Image
      #   run: docker build -t dashboard .

      # - name: Scan Image
      #   run: trivy image --exit-code 1 --severity CRITICAL,HIGH dashboard
      #   # run: trivy image --exit-code 1 --severity CRITICAL,HIGH kienkt/dashboard-react-app:latest
      
      # - name: Build docker container  
      #   run: docker run --name dashboard-app -dp 8000:80 dashboard
      
      # - name: Stop and remove docker container
      #   run: |
      #     docker stop dashboard-app
      #     docker rm dashboard-app

      # # - name: Login to GitHub Container Registry
      # #   uses: docker/login-action@v3
      # #   with:
      # #     registry: ghcr.io
      # #     username: ${{ github.repository_owner }}
      # #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tagging image
      #   run: |
      #     docker tag dashboard kienkt/dashboard-app:v1.${{ github.run_number }} 
      #     docker tag dashboard kienkt/dashboard-app:latest
      
      # - name: Push image to registry
      #   run: |
      #     docker push kienkt/dashboard-app:v1.${{ github.run_number }}
      #     docker push kienkt/dashboard-app:latest
      #     docker rmi kienkt/dashboard-app:v1.${{ github.run_number }} kienkt/dashboard-app:latest dashboard
  # Test:
  #   # runs-on: self-hosted # Or [self-hosted, label-1] 
  #   runs-on: [self-hosted, label-3] 
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - name: Printf
  #       run: |
  #         echo "This is job Test in Scan Image workflow"


##  Scan Dockerfile -> Build image -> Scan image -> Build docker container -> Test -> Stop && rm container -> Tag image
##  Login Docker hub or ghcr.io -> push Dockerhub or ghcr.io