name: Demo
on: [push]
jobs:
  Test1:
    # runs-on: self-hosted # Or [self-hosted, label-1] 
    runs-on: [self-hosted] 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Check version Trivy
        run: |
          pwd 
          trivy --version
          echo ${{ github.workspace }}
          echo ${{ github.action}}
          echo ${{ github.job }}
          echo ${{ github.run_number}}

  Test2:
    # runs-on: self-hosted # Or [self-hosted, label-1] 
    runs-on: [self-hosted] 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


##  Scan Dockerfile -> Build image -> Scan image -> Build docker container -> Test -> Stop && rm container -> Tag image
##  Login Docker hub or ghcr.io -> push Dockerhub or ghcr.io